
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jspfbcnpuojyhjattvrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzcGZiY25wdW9qeWhqYXR0dnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzMyODUsImV4cCI6MjA2MTcwOTI4NX0.Jl8uwcyEoxR5XLtr2NDniYJ9o-iLwpCqKFToaEwzFW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
    // Using correct property for redirect URL
    redirectTo: `https://getclinics.org/auth/callback`
  }
});
